version: '3'

services:
  db_pg:
    container_name: pg_db
    user: root
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRESS_DB: my_db
      PGDATA: /data/postgres
    volumes:
      - ./pg_db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    user: root
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    networks:
      - postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    restart: unless-stopped

  app:
    image: murzzik/bot_docker:bot_docker
    build: .
    restart: always
    depends_on:
      - db_pg

networks:
  postgres:
    driver: bridge
