version: '3'

services:
  db_pg:
    container_name: pg_db
    image: postgres:14-alpine
    user: root
    environment:
      POSTGRES_USER: $TG_ACCOUNT
      POSTGRES_PASSWORD: $TG_PASS
      POSTGRESS_DB: my_db
      PGDATA: /data/postgres
    volumes:
      - ./pg_db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      postgres:
        ipv4_address: 172.18.0.2
    restart: unless-stopped

  db_pg_test:
    container_name: pg_db_test
    image: postgres:14-alpine
    user: root
    environment:
      POSTGRES_USER: $TG_ACCOUNT
      POSTGRES_PASSWORD: $TG_PASS
      POSTGRESS_DB: my_db_test
      PGDATA: /data/postgres
    volumes:
      - ./pg_db_test:/data/postgres
    ports:
      - "5432:5432"
    networks:
      postgres:
        ipv4_address: 172.18.0.10
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: $TG_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $TG_PASS
    ports:
      - "5050:80"
    networks:
      postgres:
        ipv4_address: 172.18.0.3
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    restart: unless-stopped
  
  tg_bot:
    image: telegram_bot:latest
    container_name: telegram_bot
    restart: always
    environment:
      TG_ACCOUNT: $TG_ACCOUNT
      TG_PASS: $TG_PASS
    depends_on:
      - db_pg
    networks:
      - postgres

networks:
  postgres:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
