version: '3'

services:
  db_pg:
    container_name: pg_db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRESS_DB: my_db
    volumes:
      - ./db_pG:/db_local
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"