"""Модель под сайт: surrogate PK клиента, участники, accounting_id.

Revision ID: 0002_site_model
Revises: 0001_initial_as_is
Create Date: 2026-08-23
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0002_site_model"
down_revision: Union[str, None] = "0001_initial_as_is"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TABLE main.client DROP CONSTRAINT client_pkey")
    op.execute(
        "ALTER TABLE main.client ADD COLUMN id integer "
        "GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        "ALTER TABLE main.client ADD CONSTRAINT client_pkey PRIMARY KEY (id)"
    )
    op.execute(
        "ALTER TABLE main.client ADD CONSTRAINT client_phone_key UNIQUE (phone)"
    )

    op.execute("ALTER TABLE main.schedule ADD COLUMN client_id integer")
    op.execute("ALTER TABLE main.schedule ADD COLUMN accounting_id bigint")
    op.execute(
        """
        UPDATE main.schedule s
        SET client_id = c.id
        FROM main.client c
        WHERE s.client = c.phone
          AND s.client IS DISTINCT FROM -1
        """
    )

    op.execute(
        """
        CREATE TABLE main.schedule_participant (
            schedule_id integer NOT NULL,
            client_id integer NOT NULL,
            PRIMARY KEY (schedule_id, client_id)
        )
        """
    )
    op.execute(
        """
        INSERT INTO main.schedule_participant (schedule_id, client_id)
        SELECT DISTINCT s.id, c.id
        FROM main.schedule s
        CROSS JOIN LATERAL unnest(
            COALESCE(s.client_list, ARRAY[]::bigint[])
        ) AS listed(phone_number)
        JOIN main.client c ON c.phone = listed.phone_number
        """
    )
    op.execute(
        """
        INSERT INTO main.schedule_participant (schedule_id, client_id)
        SELECT DISTINCT s.id, c.id
        FROM main.schedule s
        JOIN main.client c ON c.phone = s.client
        WHERE s.client IS DISTINCT FROM -1
        ON CONFLICT DO NOTHING
        """
    )

    op.execute("ALTER TABLE main.accounting ADD COLUMN client_pk integer")
    op.execute(
        """
        UPDATE main.accounting a
        SET client_pk = c.id
        FROM main.client c
        WHERE a.client_id = c.phone
        """
    )
    op.execute("ALTER TABLE main.accounting DROP COLUMN client_id")
    op.execute("ALTER TABLE main.accounting RENAME COLUMN client_pk TO client_id")

    op.execute("ALTER TABLE main.price ADD COLUMN client_id integer")
    op.execute(
        """
        UPDATE main.price p
        SET client_id = c.id
        FROM main.client c
        WHERE p.client = c.phone
        """
    )
    op.execute("ALTER TABLE main.price DROP COLUMN client")

    op.execute(
        """
        UPDATE main.schedule s
        SET accounting_id = sub.accounting_id
        FROM (
            SELECT DISTINCT ON (s2.id)
                s2.id AS schedule_id,
                a.id AS accounting_id
            FROM main.schedule s2
            JOIN main.accounting a
              ON a.client_id = s2.client_id
             AND a.type_train_id IS NOT DISTINCT FROM s2.type_train_id
             AND a.created_at <= s2.add_time
            WHERE s2.client_id IS NOT NULL
              AND COALESCE(s2.is_group, false) = false
            ORDER BY s2.id, a.created_at DESC, a.id DESC
        ) sub
        WHERE s.id = sub.schedule_id
        """
    )

    op.execute("ALTER TABLE main.schedule DROP CONSTRAINT schedule_unique")
    op.execute("ALTER TABLE main.schedule DROP COLUMN client")
    op.execute("ALTER TABLE main.schedule DROP COLUMN client_list")
    op.execute("ALTER TABLE main.schedule ALTER COLUMN date SET NOT NULL")
    op.execute('ALTER TABLE main.schedule ALTER COLUMN "time" SET NOT NULL')
    op.execute(
        'ALTER TABLE main.schedule '
        'ADD CONSTRAINT schedule_unique UNIQUE (date, "time")'
    )

    op.execute(
        """
        ALTER TABLE main.schedule
        ADD CONSTRAINT schedule_client_id_fkey
        FOREIGN KEY (client_id) REFERENCES main.client(id)
        """
    )
    op.execute(
        """
        ALTER TABLE main.schedule
        ADD CONSTRAINT schedule_type_train_id_fkey
        FOREIGN KEY (type_train_id) REFERENCES main.trains(id)
        """
    )
    op.execute(
        """
        ALTER TABLE main.schedule
        ADD CONSTRAINT schedule_accounting_id_fkey
        FOREIGN KEY (accounting_id) REFERENCES main.accounting(id)
        """
    )
    op.execute(
        """
        ALTER TABLE main.schedule_participant
        ADD CONSTRAINT schedule_participant_schedule_id_fkey
        FOREIGN KEY (schedule_id) REFERENCES main.schedule(id)
        ON DELETE CASCADE
        """
    )
    op.execute(
        """
        ALTER TABLE main.schedule_participant
        ADD CONSTRAINT schedule_participant_client_id_fkey
        FOREIGN KEY (client_id) REFERENCES main.client(id)
        """
    )
    op.execute(
        """
        ALTER TABLE main.accounting
        ADD CONSTRAINT accounting_client_id_fkey
        FOREIGN KEY (client_id) REFERENCES main.client(id)
        """
    )
    op.execute(
        """
        ALTER TABLE main.accounting
        ADD CONSTRAINT accounting_type_train_id_fkey
        FOREIGN KEY (type_train_id) REFERENCES main.trains(id)
        """
    )
    op.execute(
        """
        ALTER TABLE main.price
        ADD CONSTRAINT price_client_id_fkey
        FOREIGN KEY (client_id) REFERENCES main.client(id)
        """
    )
    op.execute(
        """
        ALTER TABLE main.schedule
        ADD CONSTRAINT schedule_price_non_negative
        CHECK (price IS NULL OR price >= 0)
        """
    )
    op.execute(
        """
        ALTER TABLE main.accounting
        ADD CONSTRAINT accounting_summ_non_negative
        CHECK (summ IS NULL OR summ >= 0)
        """
    )
    op.execute(
        """
        ALTER TABLE main.accounting
        ADD CONSTRAINT accounting_count_train_positive
        CHECK (count_train IS NULL OR count_train > 0)
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE main.accounting DROP CONSTRAINT IF EXISTS accounting_count_train_positive"
    )
    op.execute(
        "ALTER TABLE main.accounting DROP CONSTRAINT IF EXISTS accounting_summ_non_negative"
    )
    op.execute(
        "ALTER TABLE main.schedule DROP CONSTRAINT IF EXISTS schedule_price_non_negative"
    )
    op.execute("ALTER TABLE main.price DROP CONSTRAINT IF EXISTS price_client_id_fkey")
    op.execute(
        "ALTER TABLE main.accounting DROP CONSTRAINT IF EXISTS accounting_type_train_id_fkey"
    )
    op.execute(
        "ALTER TABLE main.accounting DROP CONSTRAINT IF EXISTS accounting_client_id_fkey"
    )
    op.execute(
        "ALTER TABLE main.schedule_participant "
        "DROP CONSTRAINT IF EXISTS schedule_participant_client_id_fkey"
    )
    op.execute(
        "ALTER TABLE main.schedule_participant "
        "DROP CONSTRAINT IF EXISTS schedule_participant_schedule_id_fkey"
    )
    op.execute(
        "ALTER TABLE main.schedule DROP CONSTRAINT IF EXISTS schedule_accounting_id_fkey"
    )
    op.execute(
        "ALTER TABLE main.schedule DROP CONSTRAINT IF EXISTS schedule_type_train_id_fkey"
    )
    op.execute(
        "ALTER TABLE main.schedule DROP CONSTRAINT IF EXISTS schedule_client_id_fkey"
    )
    op.execute("ALTER TABLE main.schedule DROP CONSTRAINT IF EXISTS schedule_unique")

    op.execute("ALTER TABLE main.schedule ADD COLUMN client bigint")
    op.execute("ALTER TABLE main.schedule ADD COLUMN client_list bigint[]")
    op.execute(
        """
        UPDATE main.schedule s
        SET client_list = sub.phones
        FROM (
            SELECT sp.schedule_id,
                   array_agg(c.phone ORDER BY c.id) AS phones
            FROM main.schedule_participant sp
            JOIN main.client c ON c.id = sp.client_id
            GROUP BY sp.schedule_id
        ) sub
        WHERE s.id = sub.schedule_id
        """
    )
    op.execute(
        """
        UPDATE main.schedule
        SET client = CASE
            WHEN client_id IS NULL OR COALESCE(is_group, false) THEN -1
            ELSE (SELECT phone FROM main.client WHERE id = schedule.client_id)
        END
        """
    )

    op.execute("ALTER TABLE main.schedule DROP COLUMN accounting_id")
    op.execute("DROP TABLE IF EXISTS main.schedule_participant")
    op.execute("ALTER TABLE main.schedule DROP COLUMN client_id")
    op.execute("ALTER TABLE main.schedule ALTER COLUMN date DROP NOT NULL")
    op.execute('ALTER TABLE main.schedule ALTER COLUMN "time" DROP NOT NULL')
    op.execute(
        'ALTER TABLE main.schedule '
        'ADD CONSTRAINT schedule_unique UNIQUE (date, "time", client)'
    )

    op.execute("ALTER TABLE main.accounting ADD COLUMN client_phone bigint")
    op.execute(
        """
        UPDATE main.accounting a
        SET client_phone = c.phone
        FROM main.client c
        WHERE a.client_id = c.id
        """
    )
    op.execute("ALTER TABLE main.accounting DROP COLUMN client_id")
    op.execute("ALTER TABLE main.accounting RENAME COLUMN client_phone TO client_id")

    op.execute("ALTER TABLE main.price ADD COLUMN client bigint")
    op.execute(
        """
        UPDATE main.price p
        SET client = c.phone
        FROM main.client c
        WHERE p.client_id = c.id
        """
    )
    op.execute("ALTER TABLE main.price DROP COLUMN client_id")

    op.execute("ALTER TABLE main.client DROP CONSTRAINT client_pkey")
    op.execute("ALTER TABLE main.client DROP CONSTRAINT client_phone_key")
    op.execute("ALTER TABLE main.client DROP COLUMN id")
    op.execute(
        "ALTER TABLE main.client ADD CONSTRAINT client_pkey PRIMARY KEY (phone)"
    )
